# Generated by Django 2.2.2 on 2019-07-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Имя')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpages.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студента',
                'verbose_name_plural': 'Студенты',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='Дата')),
                ('title', models.CharField(max_length=50, verbose_name='Лекция')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpages.Group', verbose_name='Группа')),
                ('students_come', models.ManyToManyField(blank=True, related_name='students', to='testpages.Student', verbose_name='Присутствующие')),
            ],
            options={
                'verbose_name': 'Лекцию',
                'verbose_name_plural': 'Лекции',
                'ordering': ['-date'],
            },
        ),
    ]
