# Generated by Django 2.2.2 on 2019-07-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
