# Generated by Django 2.2.2 on 2019-07-07 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='lecture',
        ),
        migrations.AddField(
            model_name='lecture',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testpages.Group'),
        ),
    ]
