# Generated by Django 2.2.2 on 2019-07-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(auto_created=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpages.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Лекция'),
        ),
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpages.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя'),
        ),
    ]
