# Generated by Django 2.2.2 on 2019-07-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpages', '0002_auto_20190707_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='count',
        ),
    ]
